### ISSUE TITLE
Error introduced in 0.6.0

### ISSUE THREAD

**Issue by weshatheleopard** [TwP/logging-rails#26]
```
NameError: method `logger' not defined in ActionView::Base
[....]/gems/logging-rails-0.6.0/lib/logging/rails/mixin.rb:18:in `remove_method'
[....]/gems/logging-rails-0.6.0/lib/logging/rails/mixin.rb:18:in `included'
[....]/gems/logging-rails-0.6.0/lib/logging/rails/railtie.rb:35:in `include'
```

0.5.0 works just fine.

More info [here](https://stackoverflow.com/questions/45068612/why-does-ruby-fail-to-remove-method-even-though-it-is-clearly-defined)

**Comment by guizmaii** [comment]
Same error here.

I don't have this error with Rails 4 but only with Rails 3. Not tested on Rails 5 nor 6.
