### ISSUE TITLE
`logger' not defined in ActiveRecord::Base (NameError)

### ISSUE THREAD

**Issue by yovasx2** [TwP/logging-rails#33]
When using this gem https://github.com/newrelic/rpm
I got an error when rails is initializing:
```
/bundle/gems/logging-1.8.2/lib/logging.rb:306: warning: already initialized constant Logging::MAX_LEVEL_LENGTH
/bundle/gems/logging-1.8.2/lib/logging.rb:306: warning: previous definition of MAX_LEVEL_LENGTH was here
/bundle/gems/logging-rails-0.4.0/lib/logging/rails/mixin.rb:21:in `remove_method': method `logger' not defined in ActiveRecord::Base (NameError)
from /bundle/gems/logging-rails-0.4.0/lib/logging/rails/mixin.rb:21:in `included'
from /bundle/gems/logging-rails-0.4.0/lib/logging/rails/railtie.rb:29:in `include'
from /bundle/gems/logging-rails-0.4.0/lib/logging/rails/railtie.rb:29:in `block (2 levels) in <class:Railtie>'
from /bundle/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
from /bundle/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
from /bundle/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
from /bundle/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:44:in `each'
from /bundle/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
from /bundle/gems/activerecord-4.2.1/lib/active_record/base.rb:316:in `<module:ActiveRecord>'
from /bundle/gems/activerecord-4.2.1/lib/active_record/base.rb:26:in `<top (required)>'
from /bundle/gems/activerecord-4.2.1/lib/active_record/relation/predicate_builder.rb:118:in `<class:PredicateBuilder>'
from /bundle/gems/activerecord-4.2.1/lib/active_record/relation/predicate_builder.rb:2:in `<module:ActiveRecord>'
from /bundle/gems/activerecord-4.2.1/lib/active_record/relation/predicate_builder.rb:1:in `<top (required)>'
from /bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
from /bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
from /bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
from /bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
from /bundle/gems/activesupport-4.2.1/lib/active_support/dependencies/autoload.rb:70:in `block in eager_load!'
from /bundle/gems/activesupport-4.2.1/lib/active_support/dependencies/autoload.rb:70:in `each_value'
from /bundle/gems/activesupport-4.2.1/lib/active_support/dependencies/autoload.rb:70:in `eager_load!'
from /bundle/gems/activerecord-4.2.1/lib/active_record.rb:158:in `eager_load!'
from /bundle/gems/railties-4.2.1/lib/rails/application/finisher.rb:56:in `each'
from /bundle/gems/railties-4.2.1/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
from /bundle/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
from /bundle/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
from /bundle/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
from /usr/local/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
from /usr/local/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
from /usr/local/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
from /usr/local/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
from /usr/local/lib/ruby/2.2.0/tsort.rb:345:in `each'
from /usr/local/lib/ruby/2.2.0/tsort.rb:345:in `call'
from /usr/local/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
from /usr/local/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
from /usr/local/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
from /bundle/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
from /bundle/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
from /onelogin/src/config/environment.rb:5:in `<top (required)>'
from /onelogin/src/config.ru:3:in `require'
from /onelogin/src/config.ru:3:in `block in <main>'
from /bundle/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
from /bundle/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
from /onelogin/src/config.ru:in `new'
from /onelogin/src/config.ru:in `<main>'
from /bundle/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
from /bundle/gems/rack-1.6.0/lib/rack/builder.rb:49:in `new_from_string'
from /bundle/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
from /bundle/gems/rack-1.6.0/lib/rack/server.rb:299:in `build_app_and_options_from_config'
from /bundle/gems/rack-1.6.0/lib/rack/server.rb:208:in `app'
from /bundle/gems/railties-4.2.1/lib/rails/commands/server.rb:61:in `app'
from /bundle/gems/rack-1.6.0/lib/rack/server.rb:336:in `wrapped_app'

```

**Comment by marat-y** [comment]
@yovasx2 hey, have you ever solved this issue?

`/bundle/gems/logging-1.8.2/lib/logging.rb:306: warning: already initialized constant Logging::MAX_LEVEL_LENGTH`

**Comment by yovasx2** [comment]
I think so, I don't really remember, but it seems that you need to define the logger before new_relic can delete it
