### ISSUE TITLE
For Ruby 3.2.2 and Rails 7 undefined method `exists?' for File:Class (NoMethodError)

### ISSUE THREAD

**Issue by fernandoiwamoto** [TwP/logging-rails#39]
/home/fernando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/logging-rails-0.6.0/lib/logging/rails/railtie.rb:18:in `block in <class:Railtie>': undefined method `exists?' for File:Class (NoMethodError)

      load file if File.exists? file
                       ^^^^^^^^
Did you mean?  exist?
	from /home/fernando/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8.1/lib/rails/initializable.rb:32:in `instance_exec'

I am using 0.6.0 of this gem + rails 7.0.8.1 and ruby 3.2.2

I think the `exists` is removed from ruby 3.0.0 / rails 7.

**Comment by lilfaf** [comment]
Hi @fernandoiwamoto here is a workaround for this issue

`lib/logging_railtie_patch.rb`:

```ruby
# frozen_string_literal: true

require 'logging/rails/railtie'

module LoggingRailtiePatch
  def self.override_initializer!
    Logging::Rails::Railtie.class_eval do
      # Remove the existing initializer
      initializers.delete_if { |initializer| initializer.name == 'logging.configure' }

      # Add the new initializer
      initializer 'logging.configure', before: 'initialize_logger' do |app|
        file = ::Rails.root.join('config/logging.rb')
        load file if File.exist? file
        ::Logging::Rails.configuration&.call(app.config)
      end
    end
  end
end

LoggingRailtiePatch.override_initializer!
```

`config/application.rb`:

```ruby
# frozen_string_literal: true

require_relative 'boot'

require 'rails'
# ...

Bundler.require(*Rails.groups)

# Import patch after bundler and before app init
require File.expand_path('../lib/logging_railtie_patch', __dir__)

class Application < Rails::Application
  # ...
end
```

**Comment by stefanwork** [comment]
Here's my workaround, put this somewhere early in your app's initialization:

```ruby
# Ruby 3.2 removed File.exists?, but logging-rails uses it. https://github.com/TwP/logging-rails/issues/39
unless File.respond_to?(:exists?)
  class << File
    alias_method :exists?, :exist?
  end
end
```
